// Run with PGLITE_MODULE pointing to an installed @electric-sql/pglite module.
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const { PGlite } = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db = new PGlite();
const s1 = '00000000-0000-0000-0000-000000000001';
const s2 = '00000000-0000-0000-0000-000000000002';
const c1 = '00000000-0000-0000-0000-000000000003';
const c2 = '00000000-0000-0000-0000-000000000004';
const newcomer = '00000000-0000-0000-0000-000000000005';
async function actor(id, role = 'authenticated') {
  await db.exec(`RESET ROLE; SET ROLE ${role};`);
  await db.query("SELECT set_config('request.jwt.claim.sub', $1, false), set_config('request.jwt.claim.role', $2, false)", [id, role]);
}
try {
  await db.exec(`
    CREATE ROLE anon; CREATE ROLE authenticated;
    CREATE SCHEMA auth;
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql AS $$ SELECT current_setting('request.jwt.claim.role', true) $$;
    GRANT USAGE ON SCHEMA public, auth TO anon, authenticated;
    CREATE TABLE profiles (id uuid PRIMARY KEY, name text NOT NULL, role text NOT NULL);
    INSERT INTO profiles VALUES ('${s1}', 'Student one', 'student'), ('${s2}', 'Student two', 'student'), ('${c1}', 'Counselor one', 'counselor'), ('${c2}', 'Counselor two', 'counselor');
    ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
    GRANT SELECT, INSERT, UPDATE ON profiles TO authenticated;
    CREATE POLICY profile_read ON profiles FOR SELECT TO authenticated USING (id = auth.uid() OR auth.uid() IN ('${c1}', '${c2}'));
    CREATE POLICY profile_insert ON profiles FOR INSERT TO authenticated WITH CHECK (id = auth.uid());
    CREATE POLICY profile_update ON profiles FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
  `);
  await db.exec(await readFile(new URL('../supabase/migrations/006_counselor_support.sql', import.meta.url), 'utf8'));
  await actor(s1);
  await assert.rejects(db.query('UPDATE profiles SET role = $1 WHERE id = $2', ['counselor', s1]));
  await actor(newcomer);
  await db.query('INSERT INTO profiles VALUES ($1, $2, $3)', [newcomer, 'New user', 'counselor']);
  assert.equal((await db.query('SELECT role FROM profiles WHERE id=$1', [newcomer])).rows[0].role, 'student');
  await actor(c1);
  await db.query('INSERT INTO counselor_availability VALUES ($1, true)', [c1]);
  await assert.rejects(db.query('INSERT INTO counselor_availability VALUES ($1, true)', [c2]));
  await actor(s1);
  const directory = await db.query('SELECT * FROM messaging_contacts()');
  assert.equal(directory.rows.length, 2);
  assert.equal((await db.query('SELECT * FROM profiles WHERE id=$1', [c1])).rows.length, 0);
  await assert.rejects(db.query('SELECT start_conversation($1)', [c2]));
  const conversation = (await db.query('SELECT start_conversation($1) AS id', [c1])).rows[0].id;
  assert.equal((await db.query('SELECT start_conversation($1) AS id', [c1])).rows[0].id, conversation);
  const messageId = '00000000-0000-0000-0000-000000000010';
  await db.query('INSERT INTO messages (id, conversation_id, body) VALUES ($1, $2, $3)', [messageId, conversation, 'Please help']);
  await assert.rejects(db.query('INSERT INTO messages (conversation_id, sender_id, body) VALUES ($1, $2, $3)', [conversation, c1, 'Spoofed']));
  await assert.rejects(db.query('INSERT INTO messages (conversation_id, body) VALUES ($1, $2)', [conversation, '   ']));
  await assert.rejects(db.query('INSERT INTO messages (conversation_id, body) VALUES ($1, $2)', [conversation, 'x'.repeat(4001)]));
  await actor(s2);
  assert.equal((await db.query('SELECT * FROM messages')).rows.length, 0);
  assert.equal((await db.query('SELECT * FROM conversations')).rows.length, 0);
  await assert.rejects(db.query('INSERT INTO messages (conversation_id, body) VALUES ($1, $2)', [conversation, 'Intrusion']));
  await db.query('SELECT mark_messages_read($1)', [[messageId]]);
  await actor(c2);
  assert.equal((await db.query('SELECT * FROM messages')).rows.length, 0);
  assert.equal((await db.query('SELECT * FROM messaging_contacts()')).rows.length, 0);
  await actor(c1);
  assert.equal((await db.query('SELECT * FROM messages')).rows[0].read_at, null);
  await db.query('SELECT mark_messages_read($1)', [[messageId]]);
  assert.ok((await db.query('SELECT * FROM messages')).rows[0].read_at);
  await db.query('INSERT INTO messages (conversation_id, body) VALUES ($1, $2)', [conversation, 'I can help']);
  await db.query('UPDATE counselor_availability SET accepting_requests = false WHERE counselor_id=$1', [c1]);
  await actor(s1);
  assert.equal((await db.query('SELECT start_conversation($1) AS id', [c1])).rows[0].id, conversation);
  await assert.rejects(db.query('INSERT INTO priority_reviews (student_id, priority, rationale) VALUES ($1, $2, $3)', [s1, 'routine', 'Self review']));
  await actor(c1);
  await db.query('INSERT INTO priority_reviews (student_id, priority, rationale) VALUES ($1, $2, $3)', [s1, 'follow_up', 'Arrange a check-in']);
  assert.equal((await db.query('SELECT * FROM priority_reviews')).rows[0].reviewer_id, c1);
  await assert.rejects(db.query('UPDATE priority_reviews SET priority=$1', ['routine']));
  await assert.rejects(db.query('DELETE FROM priority_reviews'));
  await assert.rejects(db.query('INSERT INTO priority_reviews (student_id, priority, rationale) VALUES ($1, $2, $3)', [c2, 'routine', 'Invalid student']));
  await actor(s1);
  assert.equal((await db.query('SELECT * FROM priority_reviews')).rows.length, 0);
  await actor('', 'anon');
  await assert.rejects(db.query('SELECT * FROM messages'));
  await assert.rejects(db.query('SELECT * FROM priority_reviews'));
  await assert.rejects(db.query('SELECT * FROM messaging_contacts()'));
  console.log('Database checks passed: role protection, participant isolation, availability, identity spoofing, read receipts, immutable reviews, and anonymous access.');
} finally { await db.close(); }
